language: node_js
node_js:
  - "0.10"
env:
  - DISPLAY=:99.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install casperjs
  - wget http://download.slimerjs.org/nightlies/latest-slimerjs-master/slimerjs-0.10.0pre-linux-x86_64.tar.bz2
  - tar x -C /tmp -f slimerjs-0.10.0pre-linux-x86_64.tar.bz2
  - export PATH=$PATH:/tmp/slimerjs-0.10.0pre
script:
  - make test
